replicaCount: 1

image:
  repository: robertobreuer/notificaciones
  tag: 5b6c1a5
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
